### ISSUE TITLE
How to work with RealmRecyclerViewAdapter in this scene?

### ISSUE THREAD

**Issue by Misayanice** [realm/realm-android-adapters#102]
1. public class IndexObjBean{
          private int pageNumber;
          private RealmList<IndexResultBean> result;
   }
   public class IndexResultBean{
          private String info;
   }

2.Load IndexResultBean in a list，Each network requests ten data into IndexResultBean table(pull  load more)

3. I want to addChangeListener to RealmList<IndexResultBean>,  UI and table change together.
How to monitor changes in the entire list？

**Comment by nhachicha** [comment]
@Misayanice  When you create the `RealmRecyclerViewAdapter` you pass as an argument the `RealmList`,  and a `boolean` (`autoUpdate`), this will internally register a listener for your `RealmList` to react to changes (`notifyItemRangeRemoved` / `notifyItemRangeInserted` and `notifyItemRangeChanged`) https://github.com/realm/realm-android-adapters/blob/2f1c060fa90b7797fc2e83bcbe283912135a36e2/adapters/src/main/java/io/realm/RealmRecyclerViewAdapter.java#L43-L70

You're also free to register a `OrderedRealmCollectionChangeListener` on the `RealmList` outside the adapter, to receive such notifications.

**Comment by Misayanice** [comment]
ok!
