### ISSUE TITLE
How will the cached data, and then displayed on the recyclerview.

### ISSUE THREAD

**Issue by Misayanice** [realm/realm-android-adapters#103]
Such a scene, how do I update. For example, I load the N page data from the network and cache to the database, and then use RealmBaseAdapter to display UI. Then I go back
 When I am offline, I need to display the data in the database on the recyclerview, How to deal with RealmBaseAdapter？

**Comment by nhachicha** [comment]
Your Adapter always load data from Realm, this gives you the possibility to load the existing data, while offline.

Your network layer should update the model only (Realm). Internally you can choose to build the `RealmBaseAdapter` to register internally a listener, to notify the view to update once the model is updated

**Comment by Zhuinden** [comment]
@Misayanice you need to listen to changes in the local datasource, and the `RealmBaseAdapter` does exactly that if you provide it a `RealmResults`. That way, your caching and database persistence are both one and the same.

In that case, you only need to check if you actually need to download the data from the network.

**Comment by Misayanice** [comment]
There's a big problem here. For example, when I first started the network, the first set of monitoring, such as new RealmRecyclerViewAdapter (realm.where (Counter.class))
FindAllSortedAsync (Counter.FIELD_COUNT), I need to insert ten data each time (copyToRealm) to the database, this monitor is to monitor all the data changes, so no problem. When I do not have the network, I want to load 10 data from the database, how to set the 10 data to UI, through the new RealmRecyclerViewAdapter (realm.where (Counter.class))
FindAllSortedAsync (Counter.FIELD_COUNT)"

**Comment by Zhuinden** [comment]
If you write the data into the Realm that you've downloaded, then such query will show the data that has previously been saved into the Realm, without having to differentiate between whether you have network access or not.

**Comment by Misayanice** [comment]
1.public class A1 extends RealmObject {
    private int id ;
    private RealmList<B1> b1;

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public RealmList<B1> getB1() {
        return b1;
    }

    public void setB1(RealmList<B1> b1) {
        this.b1 = b1;
    }
}
public class B1 extends RealmObject {
    private int id;

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }
}


2 as mentioned above, for example, I have N twitter ---->List<A1>, each tweet has M comments --->List<B1>, I need to set A1, B1 to Recyclerview
. At this point, I need to listen to twitter changes, including changes to List<A1> and List<B1>, such as deleting a tweet, deleting a comment. How to deal with RealmRecyclerviewAdapter?

**Comment by Misayanice** [comment]
You don't understand me, because the logic needs to use the same Recyclerview and RealmRecyclerview. When I have a network when I perform is to insert and update; when I am not net, I perform query. How to update the query data to new RealmReyclerviewAdapter (realm.where (Counter.class))
FindAllSortedAsync (Counter.FIELD_COUNT)

**Comment by Misayanice** [comment]
You don't understand me, because the logic needs to use the same Recyclerview and RealmRecyclerviewAdapter. When I have a network when I perform is to insert and update; when I am not net, I perform query. How to update the query data to new RealmReyclerviewAdapter (realm.where (Counter.class))
FindAllSortedAsync (Counter.FIELD_COUNT)

**Comment by beeender** [comment]
is the query same for both online/offline?

**Comment by Zhuinden** [comment]
> When I have a network when I perform is to insert and update

When you insert / update you still show the same query results, no? There should be no distinction between when you do have internet access and when you don't - in respect to Realm.

**Comment by Misayanice** [comment]
online----->  realm.copyToRealmOrUpdate(list)----->RealmRecyclerViewAdapter,OrderedRealmCollectionChangeListener's onChange--->insert
ofline------>I can query the data------->How to update to UI via RealmRecyclerViewAdapter？

**Comment by Misayanice** [comment]
@beeender yes

**Comment by beeender** [comment]
If the query is the same, the queried Results won't be changed. Why do you need to update the view?

**Comment by Zhuinden** [comment]
You don't need to update the view manually, RealmRecyclerViewAdapter does that.

**Comment by Misayanice** [comment]
@beeender Because offline can only read cache, cache to show to the interface, this is our cache logic

**Comment by Zhuinden** [comment]
You don't need to use a cache if you use RealmResults + RealmRecyclerViewAdapter

**Comment by Misayanice** [comment]
@Zhuinden To make a long story short，I need to update the cached data to UI, how to deal with RealmRecyclerViewAdapter？

**Comment by Zhuinden** [comment]
If you make any changes to the Realm, then `RealmRecyclerViewAdapter` will display those changes in the RecyclerView automatically.

**Comment by Misayanice** [comment]
You don't need to use a cache if you use RealmResults + RealmRecyclerViewAdapter----"cache"="realm cache"

**Comment by dalinaum** [comment]
Hello @Misayanice

Did you solve your problem? If you saves the data you received from the network in Realm, RealmRecyclerViewAdapter will display the data without any network and you do not need a separate cache.

Do you have a separate cache system?

**Comment by beeender** [comment]
close due to no response
