### ISSUE TITLE
Multiple view types on RecyclerView adapter?

### ISSUE THREAD

**Issue by n2316090** [realm/realm-android-adapters#106]
Following the [example RecyclerView adapter](https://github.com/realm/realm-android-adapters/blob/master/example/src/main/java/io/realm/examples/adapters/ui/recyclerview/MyRecyclerViewAdapter.java), is there any way to have multiple view types?

In other words, a Realm RecyclerView adapter version of this:

http://stackoverflow.com/questions/26245139/how-to-create-recyclerview-with-multiple-view-type

**Comment by beeender** [comment]
Yes, the implementation will just be similar to the answer in your posted SO question. You can override relative method in `RealmRecyclerViewAdapter` to achieve it. You can also write you own adapter to do that, `RealmRecyclerViewAdapter` is actually very simple implementation, you can see the source code here : https://github.com/realm/realm-android-adapters/blob/master/adapters/src/main/java/io/realm/RealmRecyclerViewAdapter.java
