### ISSUE TITLE
Flicker with autoUpdate as true 

### ISSUE THREAD

**Issue by letronje** [realm/realm-android-adapters#107]
By default, the RealmRecyclerViewAdapter uses a `notifyItemRangeChanged` for modifications. In our case, the Realm object backing the row in the recycler view has other fields that get written to, in the background. These fields are not referred to while rendering the view for that row. But we see flicker( particularly for images) going top to bottom when these non-UI fields are changed.

As a way around, we turned `autoUpdate` off and now use a custom `OrderedRealmCollectionChangeListener` that calls a `notifyDataSetChanged` on the adapter when `changeSet` is null or when there are `changeSet.changeRanges`. This gets rid of the flickers during modifications and the expected side effect of there being no animations when rows change positions. Additions/Deletions show animations as before.

What would be a better way to avoid the flicker without sacrificing animations ?

We use picasso for images.

```
    // copied from RealmRecyclerViewAdapter
    val listener = OrderedRealmCollectionChangeListener<RealmResults<Model>>{ _, changeSet ->
        log("list changed, insertions: ${changeSet?.insertionRanges?.size}, deletions: ${changeSet?.deletionRanges?.size}, changes: ${changeSet?.changeRanges?.size}")
        
        // null Changes means the async query returns the first time.
        if((changeSet == null) || changeSet.changeRanges.isNotEmpty()){
            adapter?.notifyDataSetChanged()
            return@OrderedRealmCollectionChangeListener
        }

        // For deletions, the adapter has to be notified in reverse order.
        for(range in changeSet.deletionRanges.reversed()){
            adapter?.notifyItemRangeRemoved(range.startIndex, range.length)
        }

        for(range in changeSet.insertionRanges){
            adapter?.notifyItemRangeInserted(range.startIndex, range.length)
        }

//        for(range in changeSet.changeRanges){
//            adapter?.notifyItemRangeChanged(range.startIndex, range.length)
//        }
    }
```

**Comment by beeender** [comment]
I am thinking about add a param (refreshOnModification = false) for `RealmRecyclerViewAdapter` constructor then the recycle view adapter won't handle the modification refreshes. instead you can register a listener on the individual `RealmObject` and refresh the only changed fields for the view holder. I think that can solve your problem?

**Comment by consp1racy** [comment]
https://github.com/realm/realm-android-adapters/issues/21 would solve the flashes.

**Comment by Zhuinden** [comment]
Actually, this is a bit tricky; the `OrderedRealmCollectionChangeListener`'s `ChangeSets` should be ignored, and a `RealmObjectChangeListener` should be used per each displayed element which should be retained by their corresponding view holder.

**Comment by cmelchior** [comment]
I'm starting to lean towards the idea that we need an option for enabling `ObjectChangeSet`s even for RealmCollectionChangeListeners. That would make it possible to send them through as payloads so only sections of the UI can be refreshed.

I'm a bit concerned about the performance though as calculating ObjectChangeSets for large collections are probably going to be prohibitively expensive.

**Comment by beeender** [comment]
That would be very expensive especially when you have nested links and a hug `RealmList` field. I believe based on current API, we can make it more user friendly with data bindings out of realm-java, i mean making help classes in the adapter lib instead. 
Implementing it in the adapter means:
We would know which specific object will be shown on the screen and only subscribe to those objects.

**Comment by Zhuinden** [comment]
I think disabling automatic call to `notifyItemRangeChanged()` as a prameter would be sufficient

**Comment by consp1racy** [comment]
@Zhuinden Not if the items actually changed or even if any items switched positions. It depends on the view holder implementation, some say, it shouldn't hold the actual data. You should set a custom click delegate and pass the `ViewHolder.adapterPosition`.

@beeender Perhaps using a `RecyclerView.OnChildAttachStateChangeListener`, that might actually work.
