### ISSUE TITLE
Realm does not support INSENSITIVE sort for other languages

### ISSUE THREAD

**Issue by AlexanderArtemov** [realm/realm-android-adapters#109]
Is it realistic to wait for this in the future?

**Comment by dalinaum** [comment]
Hi @AlexanderArtemov 

Realm currently doesn't support case insensitive searches for non-latin characters. 
https://realm.io/docs/java/0.79.0/#current-limitations

If we use default ICU on Realm, it needs 16MiB at least. (http://userguide.icu-project.org/packaging) We are investigating some idea and any progress is tracked here: #1031
