### ISSUE TITLE
Fatal Singnal Exception

### ISSUE THREAD

**Issue by saeedrooyekhat** [realm/realm-android-adapters#126]
Since I used realm-adapter in the project, i encountered this error

```java
Signal 6 (SIGABRT) at 0x00000339 (code=0), thread 31623 (net.iGap)
```
also another number of Signal error -> Signal 11 , Signal 7 
I really do not have any idea for this error

In addition i used from cpu filtering in this project
i don't know this is important for this issue or no.
```java
 ndk {
      abiFilters "armeabi-v7a", "x86"
 }
```
is there any idea for this issue?

----------------------------------
Realm version(s): 3.5.0

Android Studio version: 2.2.1

Which Android version and device: all

**Comment by beeender** [comment]
Can you share the full backtrace?

**Comment by RooyeKhat** [comment]
+1

**Comment by cmelchior** [comment]
Closing due to no response
