### ISSUE TITLE
Remove first item from RealmRecyclerView

### ISSUE THREAD

**Issue by scifinder** [realm/realm-android-adapters#127]
Hello! I use this code to delete an item from RealmRecyclerView:

```
public void onBindViewHolder(NotesViewHolder holder, int position) {
    final RealmElement obj = getItem(position);
    if(obj != null) {
            
		...
			
        holder.deleteButton.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                    
				...
					
                Realm realm = Realm.getDefaultInstance();
                realm.beginTransaction();
                obj.deleteFromRealm();
                realm.commitTransaction();
                notifyDataSetChanged();
                                            
            }
        });
    }
}
```

This works fine for items in the middle and at the end of the list. However, if I delete the first item, the latter, rather than the second one, becomes its place. For example: before removing, it was A - B - C - D, after removal was D - B - C.

**Comment by Verteletsky** [comment]
I solved the problem. 

MyRecyclerViewAdapter(OrderedRealmCollection<Counter> data) {
        super(data, true);
        setHasStableIds(true);
    }

Write me, verteletsky@bitrix24.ru

**Comment by scifinder** [comment]
@Verteletsky 
I had it from the beginning.

```
    MyRecyclerViewAdapter(OrderedRealmCollection<RealmElement> data, Context ctx) {
        super(data, true);
        this.mContext = ctx;
        setHasStableIds(true);
    }
```

But it don't work for me.

**Comment by Verteletsky** [comment]
@scifinder Go telegram, take my code from bitbucket 

public RvRealmAdapter(RealmList<TaskItem> list, Context context, OnStartDragListener dragStartListener, Realm realm) {
        setHasStableIds(true);
        currentDate = new Date();
        this.list = list;
        this.context = context;
        this.dragStartListener = dragStartListener;
        this.realm = realm;
    }

В итоге я ушел от их адаптера и пишу свой.
