### ISSUE TITLE
is there any update to this repo?

### ISSUE THREAD

**Issue by jmrbcu** [realm/realm-android-adapters#131]
Is someone updating this repo, for instance, support for RxJava2 wit Realm?

**Comment by cmelchior** [comment]
RxJava2 support was released with Realm Java 4.0.0 https://github.com/realm/realm-java/blob/master/CHANGELOG.md#400-2017-10-16

This repo should work fine with both RxJava1 and 2?

**Comment by Zhuinden** [comment]
RealmRecyclerViewAdapter already handles automatic updates internally using OrderedRealmCollectionChangeListener, so there isn't really a point in making it use Rx for the sake of using Rx.

The library is compatible with Realm 3.x and 4.x alike.
