### ISSUE TITLE
`getItemIndex()` returns index instead of NO_ID

### ISSUE THREAD

**Issue by cmelchior** [realm/realm-android-adapters#132]
`getItemIndex` should only return something else than `NO_ID` if `hasStableIds()` is set. We returned `index` as the default even with `setStableIds()` as false.

**Comment by cmelchior** [comment]
Fixed by #133

**Comment by Zhuinden** [comment]
Now the readme still shows 2.1.0 :p

**Comment by cmelchior** [comment]
Ups, fixed 😛
