### ISSUE TITLE
Refector Android Support to AndroidX

### ISSUE THREAD

**Issue by Dean79000** [realm/realm-android-adapters#147]
#### Goal
Refector Android Support to AndroidX
https://developer.android.com/topic/libraries/support-library/refactor

#### Expected Results

Usage of AndroidX

#### Actual Results

Android Support v7, ...

**Comment by cmelchior** [comment]
Yes, we should do this, but probably need to wait until it is stable. In the meantime, there is the automatic dependency translator in Android Studio 3.2-alpha14 as described in https://android-developers.googleblog.com/2018/05/hello-world-androidx.html

**Comment by ogtimothymiller** [comment]
It is impossible to use the latest Android support library - only released on AndroidX - with Realm, as we can no longer use custom Adapters with realm. It expects classes from the old android.support libraries.

**Comment by AndroFlo** [comment]
I make a PR for this https://github.com/realm/realm-android-adapters/pull/151

**Comment by thatrun** [comment]
How am I supposed to migrate to androidX? Since it's been considered as stable

**Comment by Yayo-Arellano** [comment]
Need this, app cannot compile now

**Comment by Zhuinden** [comment]
You should use Jetifier for AndroidX support to use libraries that use Support Library stuff.

Realm was totally correct with waiting for AndroidX to be more popular, because Support Library can be used even in AndroidX projects with Jetifier, but AndroidX cannot be used in Support Library-using projects.

**Comment by cmelchior** [comment]
4.0.0 was released which moved all dependencies to AndroidX
