### ISSUE TITLE
RealmRecyclerViewAdapter uses RealmObject instead of RealmModel

### ISSUE THREAD

**Issue by NitroG42** [realm/realm-android-adapters#29]
In the RealmRecyclerViewAdapter : 
`public abstract class RealmRecyclerViewAdapter<T extends RealmObject, VH extends RecyclerView.ViewHolder> `
But T should extends RealmModel instead (like the RealmBaseAdapter).

**Comment by dalinaum** [comment]
Hello, @NitroG42 Thanks for reporting. #32 will resolve this.
