### ISSUE TITLE
not find io.realm:android-adapter:1.0.0

### ISSUE THREAD

**Issue by myeonginwoo** [realm/realm-android-adapters#4]
my app used ralmBaseAdapter. 
i was update realm (0.9.0). and added " compile 'io.realm:android-adapters:1.0.0' "

now cannot build

**Error:Could not find io.realm:android-adapters:1.0.0.**

why cannot build?

**Comment by stk1m1** [comment]
Hi @myeonginwoo 

There is possibly a duplicated issue here [#2731](https://github.com/realm/realm-java/issues/2731). It will be fixed soon, and you can also find an emergency fix there.

**Comment by cmelchior** [comment]
Version 1.0.1 should now be available in JCenter. Sorry for the trouble.
