### ISSUE TITLE
Use RealmModel instead of RealmObject in RealmRecyclerViewAdapter

### ISSUE THREAD

**Issue by hardysim** [realm/realm-android-adapters#41]
With the release of realm 1.0.0 it seems to be cool to switch to this lib here but I cannot use it right away as I've changed all my model-classes to implement `RealmModel` rather than extend from `RealmObject` for more flexibility.

Are there any complications when using `RealmRecyclerViewAdapter` with `RealmModel`? It would be a minimal change like:

`RealmRecyclerViewAdapter<T extends RealmModel, [...]`

Can you change it?

**Comment by cmelchior** [comment]
That issue should be fixed in 1.2.2 of the Android Adapters. What version are you using?

**Comment by hardysim** [comment]
I'm using 1.2.1 - copied from the README ;-)
Seems working with 1.2.2.

THX

---

For the docs: This is duplicated with #29.
