### ISSUE TITLE
The content of the adapter has changed but ListView did not receive a notification. 

### ISSUE THREAD

**Issue by beeender** [realm/realm-android-adapters#48]
Thanks a lot for @KynoYang help for reproducing this bug with a demo project, see https://github.com/KynoYang/RealmBaseAdapterDemo

To reproduce the issue with Realm's sample project see https://github.com/realm/realm-android-adapters/commit/92ae08a6803d681ba9752818fc5cc07039668ddd
By scrolling the list view, a exception will be thrown:

```
java.lang.IllegalStateException: The content of the adapter has changed but ListView did not receive a notification. Make sure the content of your adapter is not modified from a background thread, but only from the UI thread. Make sure your adapter calls notifyDataSetChanged() when its content changes. [in ListView(2131492945, class android.widget.ListView) with Adapter(class io.realm.examples.adapters.ui.listview.MyListAdapter)]
                                                                              at android.widget.ListView.layoutChildren(ListView.java:1562)
                                                                              at android.widget.AbsListView.onTouchMove(AbsListView.java:3743)
```

---

Tow scenarios needed to be considered for this issue:

1) The change made by async transaction. The `RealmResults` should be updated to the realm version when `REALM_CHANGED` arrived. Issue with it should be fixed by PR https://github.com/realm/realm-java/pull/2926

2) The change made by synced transaction. See https://github.com/realm/realm-android-adapters/commit/89f7fe46057397ace4236876de7f1ae3962e095e

This is the difficult part. We have a chance at a moment, the `RealmResults` version is mis-matched with Realm version -- it could contain a invalid object when redraw happens.
Think below sequences:

- Remove some data from a RealmResults, `REALM_CHANGED` is sent
- a redraw event arrived to refresh list view
- crash, since the RealmResults are not refreshed which contains a deleted element
- `REALM_CHANGED` just arrived if crash doesn't happen

To fix this, maybe we can add API to the `RealmResutls.refresh()`. First, it checks if the associated Realm is in transaction, throws if it is. Then sync the tableview. And call this API in the adapter everywhere.

**Comment by cmelchior** [comment]
Good catch on #1 
I think we talked about about #2 at some point where we agreed that this was a know corner case and that people should either create a new RealmResults or use `isValid` when creating views for the adapter? Alternative use async writes, which would be best practise anyway.

I would be a bit hesitant about adding `refresh()` to RealmResults for a number of reasons:
1) It wouldn't be useful on the RealmCollection interface (e.g. RealmList doesn't need it)
2) We have moved all changelisteners to the Looper, so the semantics of `refresh()` would be weird, e.g. it would update to latest version, but not call listeners or call listeners which would be against what we tried accomplish.

**Comment by beeender** [comment]
The major problem of 2) is user might find there is a problem when using synced transaction and realm adapters -- it works already unless a redraw happens in between, like a scrolling. And there is nothing can be done from user side to prevent that, since the sequences of redraw and `REALM_CHANGED` is out of user's control.

**Comment by cmelchior** [comment]
Good point. I think this issue ties into a number of other things. I'll try to compile all of them, which will give us an better idea on how to solve it.

**Comment by beeender** [comment]
A possible fix is we use `Handler.postAtFrontOfQueue` to do the event posting for the current thread, which makes sure redraw will happen later.

**Comment by cmelchior** [comment]
@beeender See https://github.com/realm/realm-java/pull/2952

**Comment by cmelchior** [comment]
This have been fixed by https://github.com/realm/realm-java/pull/2990, which will be part of Realm Java 1.0.1
