### ISSUE TITLE
Limit Query results passed to an Adapter

### ISSUE THREAD

**Issue by tunjos** [realm/realm-android-adapters#57]
I am looking for a way to limit the List of Items in an asynchronous query.
e.g Like only returning the first 3 items.

This taken directly from your sample, asynchronously finds all Items matching the query.
`recyclerView.setAdapter(new MyRecyclerViewAdapter(this, realm.where(TimeStamp.class).findAllAsync()));`
 
I am aware that objects are lazily loaded. But I think there needs to be a way to limit the query results, especially in this case that involves an Adapter.

Is there any work around to achieve this feat?
Thanks.

**Comment by beeender** [comment]
Is it because of you only want to show the first 3 items?
If that is the case, you can modify the adapter instead

```java
long getCount() {
    int size = results.size();
    return size > =3 ? 3 : size;
```

There won't be too much benefit from memory point view by limiting the results size to some certain number in Realm size, since as you know -- it is lazy loaded :)

**Comment by tunjos** [comment]
For a RecyclerView.Adapter, That would be.
`getItemCount()`
You know I actually used this trick when with with a RecyclerView.Adapter to do something like, getItemCount() +1, so Headers could show up. :). It was trivial to simply use your suggestion.
Thanks :+1:

**Comment by beeender** [comment]
YEAH :dancers:

**Comment by flocsy** [comment]
I tried this but I got:
IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionViewHolder{41d5d1 position=11 id=-1, oldPos=10, pLpos:10 scrap [attachedScrap] tmpDetached no parent} android.support.v7.widget.RecyclerView

    final static int LIMIT = 10;

    @Override
    public int getItemCount() {
        if (mItems == null){
            return 0;
        }
        else {
            return Math.min(mItems.size(), LIMIT) + 1; //taking the footer into account
        }
    }

Without the Math.min LIMIT it worked.

**Comment by flocsy** [comment]
Never mind. I had to adjust the implementation of DiffUtil.Callback as well
