### ISSUE TITLE
Incorporating DiffUtil into RealmRecyclerViewAdapter

### ISSUE THREAD

**Issue by roughboy** [realm/realm-android-adapters#59]
As of 24.2.0, RecyclerView support library, v7 offers class called DiffUtil:
https://developer.android.com/reference/android/support/v7/util/DiffUtil.html
https://medium.com/@nullthemall/diffutil-is-a-must-797502bc1149#.26vuhgg0w

It could be used to calculate minimum set of operations when updating data in RealmRecyclerViewAdapter::updateData(OrderedRealmCollection<T>). Then the calculated set of operations can be easily dispatched directly into adapter, instead of calling very general notifyDataSetChanged() when performing RealmRecyclerViewAdapter::updateData(OrderedRealmCollection<T>).

**Comment by beeender** [comment]
Thanks for the advise!
We will investigate this. But after a quick look, we can support the target by our native fine grained notification. https://github.com/realm/realm-java/issues/989 (Well, we really should support it!)

**Comment by Zhuinden** [comment]
DiffUtil evaluates the differences on a background thread though, and managed RealmResults cannot be passed between threads. DiffUtil therefore won't work, we'll need fine-grained notifications for this from the ObjectStore.

**Comment by Zhuinden** [comment]
@hardik9850 I actually should somewhat retract that statement. Apparently [Thorben Primke's RecyclerView Library](https://github.com/thorbenprimke/realm-recyclerview/blob/master/library/src/main/java/io/realm/RealmBasedRecyclerViewAdapter.java#L479-L561) managed to solve that issue by storing the list of the IDs inside the RealmResults.

So basically he retains the list of the primary keys for every element, and then does a diff according to the list of new elements.

That can work, but you still need to obtain the primary key of every single RealmObject in the result set, and creating a proxy for each element on every change does not scale well.

**Comment by raveeshbhalla** [comment]
@Zhuinden I'm using the following approach for my application which seems to work well. Do you see any possible issues? If it looks good, would you like me to submit a PR making similar changes for your adapters?

https://gist.github.com/raveeshbhalla/efdc34ce06511ae9112770284539ea0c

**Comment by Zhuinden** [comment]
@raveeshbhalla ....wait, you can evaluate the diff on the UI thread without a problem?

Then what I said above was really really dumb :cry: however, it can definitely get laggy at larger datasets.

**Comment by raveeshbhalla** [comment]
@Zhuinden my mistake: while you can, they recommend doing it on a background thread. My application doesn't have too many list items which is why it probably worked flawlessly

**Comment by hardysim** [comment]
It would be great to have the DiffUtil-functionality in here. Can the realm-team approve and add it?

**Comment by cmelchior** [comment]
Fine-grained notification support was merged in Realm Java here: https://github.com/realm/realm-java/pull/4191 and support added to the RealmRecyclerViewAdapter here: https://github.com/realm/realm-android-adapters/pull/83

These will be part of Realm Java 3.0 and Android Adapters 2.0. 

Given that it doesn't really make sense to support DiffUtil, so I'll close this issue.

The difference with DiffUtil right now is:
* No move detection. They are represented as delete/add. See https://github.com/realm/realm-java/issues/4262
* No upper limit on changes.
* Realm run the change detection on a background automatically if you use async queries.
* No memory overhead of keeping 2 lists in memory at the same time.
