### ISSUE TITLE
Realm getting closed without calling realm.close()

### ISSUE THREAD

**Issue by Coletz** [realm/realm-android-adapters#60]
It randomly happens (1/2 times) that when I open my application the recyclerview adapter loads data correctly from realm,  but when I touch the recyclerview to scroll it everything disappear. If I try to reload data, I get the message `java.lang.IllegalStateException: This Realm instance has already been closed, making it unusable.` but I'm not closing it (I putted only a realm.close() inside activity onDestroy and fragment onStop(), but they are not called. Debugging is impossible, the app close if I put a breakpoint to try to inspect the problem. Here is the code to retrieve data and load them into realm with retrofit

```
rvAdapter = new ProfileRecyclerAdapter(this, realm.where(Profile.class).findAllSortedAsync("username");
recyclerView.setAdapter(rvAdapter);
[..]
new ServiceFactory(this).createRetrofitService(ProfileService.class)
    .downloadProfileList()
    .subscribeOn(Schedulers.newThread())
    .observeOn(AndroidSchedulers.mainThread())
    .map(this::getProfile)
    .subscribe(rx -> {
        Log.e(TAG, "Realm isClosed(): "+realm.isClosed());
        realm.executeTransactionAsync(it -> it.copyToRealmOrUpdate(rx));
    },
    error -> Log.wtf(TAG, "Error: "+error.toString())
);
```

**Comment by beeender** [comment]
Sorry for the late reply.

I am not quite familiar with rxJava, but I think `realm.executeTransactionAsync(it -> it.copyToRealmOrUpdate(rx));` could be called after `onCreate()`/`onStop`.

You can get a new instance in the `subscribe` block and close it after like:
```
.subscribe(rx -> {
        Realm realm = Realm.getDefaultInstance();
        Log.e(TAG, "Realm isClosed(): "+realm.isClosed());
        realm.executeTransactionAsync(it -> it.copyToRealmOrUpdate(rx));
        realm.close();
    },
```

**Comment by Coletz** [comment]
I was using realm in an incorrect way, the problem was given by another piece of code. I can't remember the exact fix, but I've fixed and now it works correctly, that was my fault as usual. Great job with realm guys, thanks!
