### ISSUE TITLE
Why does the RealmRecyclerViewAdapter need reference to Context?

### ISSUE THREAD

**Issue by bhargavms** [realm/realm-android-adapters#67]
#### Goal

Understand what is the purpose of the context reference in `RealmRecyclerViewAdapter` class.
#### Actual Results

When I look at the source code, the contructor just captures the reference to context in a class variable and never uses it again, later the context reference is used to create a layout inflater and I look through the code and find out that the inflater is not used anywhere either, please help me understand why the context is needed here.

**Comment by Zhuinden** [comment]
Good question. I think it just remained from `RealmBaseAdapter` in that regard, considering you can do `LayoutInflater.from(parent.getContext())` for `onCreateViewHolder`.

**Comment by bhargavms** [comment]
Well do you want me to give you a PR removing them?

**Comment by Zhuinden** [comment]
I'm not a Realm person, and it'd be a breaking change. So I'm not sure if it's worth it at the moment.

**Comment by dalinaum** [comment]
Although the context reference is not necessary indeed, it seems trivial. I'm not sure that a breaking change is worth too. How about it @realm/java ?

**Comment by cmelchior** [comment]
I think it is a mistake we still reference the Context, as it isn't used. Removing it however is a breaking change which would bump the version to `2.0.0`. I think we should wait with removing it until we got another breaking change we could bundle with it. Depending on how the API ends up that will most likely be with fine-grained notifications.

**Comment by zaki50** [comment]
How about adding abother constructor that does not take `Context`?

**Comment by cmelchior** [comment]
Sure, we could do that in the meantime and deprecate the other one.

**Comment by zaki50** [comment]
The visibility of the `layout inflater` is `protected` and I guess it is used in most of sub classes.
I changed my mind and now I think we should keep this constructor as non-deprecated.

https://github.com/realm/realm-android-adapters/pull/68/files#diff-8d85944471f7389a02ec8fb462e74fd9R42


What do you think? @bhargavms  @realm/java

**Comment by Zhuinden** [comment]
@zaki50 it makes sense in `RealmBaseAdapter`, but it doesn't make sense in `RealmRecyclerViewAdapter` because there you can use `parent.getContext()`

**Comment by dalinaum** [comment]
We can also use `parent.getContext()` in `RealmBaseAdapter.getView()` too, but we cannot prevent users who want to access `this.inflater` in `RealmBaseAdapter.getView()`, `RealmRecyclerViewAdapter.oncreateviewHolder()`, or other overrided methods.

**Comment by cmelchior** [comment]
Context has been removed from the `RealmRecyclerViewAdapter` class. Closing
