### ISSUE TITLE
Scroll to Position not working

### ISSUE THREAD

**Issue by dimparf** [realm/realm-android-adapters#75]
Hi
I am build example from this repo and add this line of code to setUpRecyclerView method:

`recyclerView.scrollToPosition(myRecyclerViewAdapter.getItemCount());
`

But scrollToPosition not working, only smoothScrollToPosition is working.
How to not smooth scroll in recycleview with RealmRecyclerViewAdapter?

**Comment by cmelchior** [comment]
When you say `scrollToPosition` does not work. What do you mean exactly by that? We don't do anything that should effect it.

**Comment by dimparf** [comment]
I expect that recyclerview scroll to position, but this is not happening. If i use smoothScrollToPosition its working (recycleview scroll to position).

**Comment by dimparf** [comment]
Sorry, this is my buggy code, close issue.
