### ISSUE TITLE
Drag and drop functionality. 

### ISSUE THREAD

**Issue by levibostian** [realm/realm-android-adapters#93]
I am using the `v2.0.0` release of the adapter. This release includes the *oh so awesome* Realm change notifications from Realm-Java v3.0. I love it. It is so smooth, thank you!

Now, I have a requirement in my app for drag and drop functionality in a Realm RecyclerView. Following the guide [found here](https://medium.com/@ipaulpro/drag-and-swipe-with-recyclerview-b9456d2b1aaf#.ibewcg377) or [here for a gist of it](http://wiki.curiosityio.com/docs/android/recyclerviews) as the top result on Google "drag and drop recyclerview". 

I have an ImageView on the left side of my RecyclerView adapter row the user touches and drags which initializes the drag and drop.

![screen shot 2017-03-06 at 4 37 31 pm](https://cloud.githubusercontent.com/assets/2041082/23633458/6e0cb432-028b-11e7-88ba-2d42d8930683.png)

I followed the above guide and it works great UI wise to get drag and drop working, however, it does not work right with the current implementation of RealmRecyclerViewAdapter. I have my RealmRecyclerViewAdapter setup so when `override fun onItemMove(fromPositionIndex: Int, toPositionIndex: Int) {` is called (indicating the user has dragged a row past another row) I am calling Realm to do a `.move()` on the RealmList used as the data set for the RealmRecyclerViewAdapter.

There are 2 UI issues that I am experiencing:

1. The user drags an item past the row directly above or below it, then, my code triggers where I call `.move()` on my RealmList data set. This call to `.move()` causes RealmRecyclerViewAdapter to call `notifyItemRangeChanged()` which makes the ImageView under the user's finger lose focus. Summary -->The user is not able to drag past 1 row. Once the user drags past just 1 row, an animation is triggered, the row the user was dragging loses focus and triggers an animation. 

2. Going with the point above, because `notifyItemRangeChanged()` is being called, the animation looks a little off. The user drags and drops a row, RealmRecyclerViewAdapter calls `notifyItemRangeChanged()` as mentioned above. This causes the list to go back to it's original order for a split second, then Realm triggers the animation via `notifyRangeChanged()`. Summary --> The user dragging and dropping animation is off because when the user drags a row past another row, for a split second the item goes back to it's original place, the Realm data set changes, then `notifyItemRangeChanged()` gets called where the animation triggers following what the user just did manually themselves dragging and dropping.

Is there a best practice to dragging and dropping with RealmRecyclerViewAdapter? Is it something that cannot be done with the existing implementation?

**Comment by Zhuinden** [comment]
It has something to do with https://github.com/realm/realm-java/issues/4245#issuecomment-282432206

**Comment by kneth** [comment]
And https://github.com/realm/realm-object-store/issues/391

**Comment by levibostian** [comment]
You guys are spot on with what my issue is. Thanks! I am subscribed to the linked issue.

**Comment by levibostian** [comment]
Close this if you feel it's a duplicate.

**Comment by cmelchior** [comment]
Yes, unfortunately, drag-n-drop isn't supported using a live Realm collection right now, but we want to fix this just as much as you do :)

I'll close it as a duplicate.

**Comment by Zhuinden** [comment]
@cmelchior I don't think this was tracked in `realm-android-adapters` though  so I am not sure if it is actually a duplicate

**Comment by cmelchior** [comment]
It wasn't, but the fix has to come from Realm-Java, more specifically: https://github.com/realm/realm-java/issues/4245

**Comment by Zhuinden** [comment]
so did calling change listener on `commitTransaction()` fix this? I mean, the `move == delete+insert` thing is still there.

**Comment by Zhuinden** [comment]
boop
